name: Build ubuntu-gcc-opt-on

on:
  push:
    branches: [master]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: "${{matrix.link}}-${{matrix.build-type}}-TLS:${{matrix.tls-provider}}"
    runs-on: ubuntu-latest
    env:
      shared: ${{matrix.link == 'SHARED' && 'ON' || 'OFF'}}
    strategy:
      fail-fast: false
      matrix:
        link: ["STATIC", "SHARED"]
        # Customize the CMake build type here (Release, Debug, RelWithDebInfo, MinSizeRel, etc.)
        build-type: ["Debug", "Release"]
        # Support (none, openssl, botan-3, auto)
        tls-provider: ["openssl", "botan-3"]

    steps:
      - name: Checkout Trantor source code
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install curl libgtest-dev libspdlog-dev libc-ares-dev openssl libssl-dev -y

      - name: Configure Cmake
        run: |
          cmake -B build -S . \
          -DCMAKE_BUILD_TYPE=${{matrix.build-type}} \
          -DBUILD_SHARED_LIBS=$shared \
          -DBUILD_MISSING_DEPENDENCIES=OFF \
          -DTRANTOR_USE_SPDLOG=ON \
          -DTRANTOR_USE_C-ARES=ON \
          -DTRANTOR_TLS_PROVIDER=${{matrix.tls-provider}} \
          -DBUILD_TESTING=ON

      - name: Build
        working-directory: ./build
        run: |
          make -j

      - name: Test
        working-directory: ./build
        run: |
          make test
