name: Build windows-msvc-opt-off

on:
  push:
    branches: [master]
  pull_request:
  workflow_dispatch:

jobs:
  no-deps-build:
    name: "${{matrix.link}}-${{matrix.build-type}}-opt-off"
    runs-on: windows-latest
    env:
      shared: ${{matrix.link == 'SHARED' && 'ON' || 'OFF'}}
    strategy:
      fail-fast: false
      matrix:
        link: ["STATIC", "SHARED"]
        # Customize the CMake build type here (Release, Debug, RelWithDebInfo, MinSizeRel, etc.)
        build-type: ["Debug", "Release"]

    steps:
      - name: Checkout Trantor source code
        uses: actions/checkout@v4
        with:
          submodules: false

      - name: Configure Cmake
        run: |
          cmake -B build -S . `
          -DBUILD_SHARED_LIBS=$shared `
          -DCMAKE_BUILD_TYPE=${{matrix.build-type}} `
          -DBUILD_MISSING_DEPENDENCIES=OFF `
          -DTRANTOR_USE_SPDLOG=OFF `
          -DTRANTOR_USE_C-ARES=OFF `
          -DBUILD_TESTING=ON `
          -G "Visual Studio 17 2022" -T host=x64 -A x64

      - name: Build
        working-directory: ./build
        # multi config build using --config to switch Release|Debug
        run: |
          cmake --build . --config ${{matrix.build-type}} --target ALL_BUILD

      - name: Test
        working-directory: ./build
        run: |
          ctest -C ${{matrix.build-type}}
